txfmtrack:
  image: fr0ntside/txfmtrack
  ports:
    - "8585:80"
  links:
    - redis
    - mongo
  volumes:
    - ./txfm-config:/var/www/txfmtrackservice-client/_config
redis:
  image: redis
mongo:
  image: mongo
